CREATE DATABASE Members;
USE Members;
CREATE TABLE Rohith(id int, id_num int, loc bigint, mob_num bigint, native varchar(10),father_name varchar(20), mother_name varchar(20), sib_name varchar(20));
CREATE TABLE Guru(id int, id_num int, loc bigint, mob_num bigint, native varchar(10),father_name varchar(20), mother_name varchar(20), sib_name varchar(20));
CREATE TABLE soha(id int, id_num int, loc bigint, mob_num bigint, native varchar(10),father_name varchar(20), mother_name varchar(20), sib_name varchar(20));
CREATE TABLE kavana(id int, id_num int, loc bigint, mob_num bigint, native varchar(10),father_name varchar(20), mother_name varchar(20), sib_name varchar(20));
CREATE TABLE Ganga(id int, id_num int, loc bigint, mob_num bigint, native varchar(10),father_name varchar(20), mother_name varchar(20), sib_name varchar(20));
select * from rohith;
DESC soha;
show tables;
