CREATE DATABASE PRODUCT;
USE PRODUCT;
CREATE TABLE DETAIL(id int,p_name varchar(10),quantity varchar(10));
SELECT * FROM DETAIL;
ALTER TABLE DETAIL ADD COLUMN P_BRAND varchar(10);
ALTER TABLE DETAIL ADD COLUMN P_NEW varchar(10);
ALTER TABLE DETAIL ADD COLUMN P_PRICE bigint;